### PR TITLE
Bands doc

### PR DESCRIPTION
**Pull request by bosonie**
Sorry for the not very clear sequence of commits. Next time I'll be better in squashing the small useless commits before pushing to git-hub.
Anyway, basically I restructured all the folder examples. Now it contains 14 informative examples that are well referenced in the documentation and clear to read and run.
All the other tests are going to be located in a folder tests in aiida_siesta_plugin (following the quantumespresso model) and they will become the unit tests. I removed them from this branch are they are not usable and I want to release the b1 version after this commit. I'll create now a new branch unitests in my fork so you will find them there.
If you fee something is missing in the examples or in the documentation, just let me know.

### CODE REVIEW

**Comment by albgar** [comment]
Thank you very much for the example work and the documentation updates.
The examples work and this first phase of the documentation upgrade looks good. I have just found a few issues:

Fixes for docs:

-- 'verd' in installation section.
-- 'this' --> 'these' in ASE and pymatgen mention
--  Basis example has split lines in entries.
-- ... default Basis: DZP plus (many) other defaults.
-- No mesh displacements possible in Kpoints??
-- Rewrite "Siesta input will present a BandPoints block". ("Will use", maybe).
-- More info on seekpath??
-- deamon --> daemon
-- run-->submit in import
-- submit  mention (in addition to run) in later example of call not using builder.
-- code argument in command line: maybe include it by default in the example.
   (Also, 'runaiida' might not be necessary)

-- In OUTPUTS, the calculation object does not have an 'out' method/field anymore,
   so calculation.out does not work.

-- CML output is activated by default by the plugin (I think)

**Comment by bosonie** [comment]
I implemented the changes.

I commented out the part about the CML output. The keyword "xml-write"  is activated by the plugin automatically. Also I think that when one compiles Siesta, the CML-writer functionality is compiled by default, right? I remember in quantum espresso there is an option to specify, but it is not the case for us, right? Otherwise, we have to reintroduce a mention to that in the documentation.
I didn't add any other info on SeeK-path. What would you like to add in particular?

In the previous comment to the pull request I forgot to mention that we have to check the band parsing in the case of spin-orbit. The .bands file shows nspin=1 and the parser works accordingly,
but I'm not sure it is correct. I open an issue about it just to remember we need to discuss it.

I'm also unsure on the utility of the example_ldos.py. We don't parse the ldos, so it might give false hopes to users. Matter of discussion as well.

**Comment by albgar** [comment]
The example script `example_ldos.py` is useful to create a LDOS file  (within a certain remote folder) for later testing of the STM plugin.

**Comment by albgar** [comment]
There are two different spellings for SeeK-path (this one seems to be the one favored by the authors). Just mention that it is a utility, now a requirement for aiida-core, to determine canonical unit cells and k-point information (or something similar).

**Comment by albgar** [comment]
Yes, the CML writing module is compiled by default in Siesta.

**Comment by albgar** [comment]
It is almost completely fine by me now. There is only one typo left: `calculation.outuputs`.

Also, the section mentioning  compilation of the CML module should go.

**Comment by bosonie** [comment]
Done. I guess it is ready to merge to the master branch. Tomorrow I'll try to release it with pypi.

**Pull request merged**
