### PR TITLE
Updated docs for BaseIterator._params_lookup

### PR DESCRIPTION
**Pull request by pfebrer96**
Wrote the docs on how to use `BaseIterator._params_lookup`.

By the way, have you thought about cleaning up the docstrings by using a first line that gives a hint of what the function class does, then a blank line, and then the rest of docs? I think it is much easier to the eye, and I believe is also the [standard for python](https://www.python.org/dev/peps/pep-0257/) :)

### CODE REVIEW

**Review by bosonie — COMMENTED** [review]
Honestly I never paid much attention to docstrings and I inherited most of them from previous developers...but yes, I'll keep it in mind! Thanks for the suggestion!
However I would reduce the white spaces in favor of indentation when you describe the various keys of  `_params_lookup`.

Should we mention in the class docstring that `_params_lookup` is a `tuple` and the groups are checked in order?

If you run yapf -i on the two files changed, the pre-commit error will disappear.

**Comment by pfebrer96** [comment]
> However I would reduce the white spaces in favor of indentation when you describe the various keys of _params_lookup.

I don't understand exactly what you mean, so you can change it if you want :)

> Should we mention in the class docstring that _params_lookup is a tuple and the groups are checked in order?

Yes! This is important, I will change it.

> If you run yapf -i on the two files changed, the pre-commit error will disappear.

Will do!

**Comment by bosonie** [comment]
I saw few more errors in the docstrings (the parts I wrote). Therefore I will review them again separately. If you just fix the pre-commits and add a line about `_params_lookup` being a tuple, I will approve and merge.

**Comment by pfebrer96** [comment]
Done!

**Review by bosonie — APPROVED** [review]
Thanks a million @pfebrer96! Don't worry about the pre-commit error. I'll fix it! I merge. Thanks!

**Pull request merged**
