### PR TITLE
Using BaseIterator for the EOS workflow

### PR DESCRIPTION
**Pull request by pfebrer96**
I adapted the EOS workflow to work with `BaseIterator`.

By doing this, the main improvement exposed to the users at the moment is that you can choose the batch size, but there may be others if the `BaseIterator` gains functionality.

During the process, I've discovered things that might be important for the `BaseIterator` to be useful to developers for creating their own workchains. I mean, to do something more than:

```python
class MyProcessIterator(BaseIterator):
    _process_class = MyProcess
``` 

One big change is that you can create iteration inputs using `cls.iteration_input()`. If I create an iteration input called "scales", for example, I allow users to do:

```python
run(Process, scales=[1,2,3,4])
```

instead of

```python
run(Process, iterate_over={"scales":[1,2,3,4]})
```

as they are exactly equivalent. This can help prevent very large nesting when you start to nest iterators, but more importantly, since an iteration input is a regular aiida input, it can be made `required` (as we need for the EOS chain, for example).

There's an extensive explanation in the docstring of `cls.iteration_input`.

Let me know what do you think!

**NOTE**: I commented out the part where `scale_to_vol` is executed because it is not working (even in the old version). It raises an error like `Molecule` has no attribute `scale_lattice`. Maybe there has been some change in pymatgen. Could you look into it? Thanks!

### CODE REVIEW

**Comment by bosonie** [comment]
I understand this. I was too optimistic in saying that to change `_process_class` was enough, but the list of changes to make is limited compared to the need of defining `<YourPlugin>Iterator`, the `_lookup_params` and so on.

In my opinion, in your approach, you load a lot of functions that you do not use. My idea is to make a collection of `parsing_func` but not to have a `_params_lookup` that contains all of them. The `SiestaIterator` can not be a universal iterator that can iterate over any possible parameter in this universe. We have to limit what  `SiestaIterator`  can do. Then, case by case, the user can create his own iterator and put in `_params_lookup` what he is interested in. For instance in `SiestaIterator`  I'm interested in iterate over the main fdf parameters, in the EosIterator over the the scales factor. If I want both at the same time, I can create a new Iterator. To keep adding functionality to `SiestaIterator`  adds confusion and is not sustainable in my opinion.

> And you can reuse the EOS workchain in both cases. What's the main difference that you see? The advantage that I saw in my case was that I didn't have to define how to parse `structure_scales` twice (in `SiestaIterator` and the EOS chain) and also I didn't have to specify `_expose_inputs_kwargs = {'exclude': ('metadata',)}` again.

Maybe for my EoS I want to expose the metadata and use a namespace.

> The main goal of this PR for me was not to update the EOS workchain, but while doing so identify weak points of the functionality of `BaseIterator` and the general infrastructure for iterators and make it more robust. So in my opinion the discussion fits in this PR, otherwise we will close it without having fully acheived the changes required. But if you insist, I will open a new one.

The only improvement I see is to have a place where to collect the `parsing_func` but I need to think what is the best way. Again in this I think the AiiDA core developer could help.

**Comment by bosonie** [comment]
> The only improvement I see is to have a place where to collect the `parsing_func` but I need to think what is the best way. Again in this I think the AiiDA core developers could help.

Maybe a `@calcfunction` factory??

**Comment by pfebrer96** [comment]
> In my opinion, in your approach, you load a lot of functions that you do not use.

Yes, but is that a problem? I mean it is not really loading anything. The `_params_lookup` variable is in `SiestaIterator` and is not copied when you inherit from it, there's always only one instance of it. So, in fact, you are using less memory than if you create a specific `_params_lookup` for your new iterator.

> The SiestaIterator can not be a universal iterator that can iterate over any possible parameter in this universe.

:laughing: 

Why not? (this is a serious question). If something can be iterated in SIESTA, why not supporting it in the `SiestaIterator`? I think that by not putting it there, you are limiting the possibilities. Someone (e.g. me) could feel annoyed by the fact that the code to iterate over two different parameters has been written but you can not use them together because they are not implemented in the same iterator. You would have to figure out how have they been implemented and create a new iterator that understands how to parse both (and do this each time this situation happens). 

So in my opinion

> For instance in SiestaIterator I'm interested in iterate over the main fdf parameters, in the EosIterator over the the scales factor.

we should not assume what future users would use `SiestaIterator` for. For me this sentence should be: "In `SiestaIterator` I'm free to iterate over whatever I want, in the `EosIterator` it only makes sense to iterate over scales, so the rest of parameters are blocked."

I agree that it is not straightforward to make it maintainable, there needs to be good organization and it has to be thought ahead. For example, what I did for structure modifications: if there is an input that accepts a structure and it's called `struct`, then all the parameters that are modifications of this structure will be `struct_<parameter>`. I believe that this is perfectly maintainable, as the "namespace" used by these parameters is perfectly defined. Even if there are two input structures `struct` and `reference`, you could still iterate over modifications of both structures at the same time without ambiguity.

> Maybe a @calcfunction factory??

Yes! but I think it's not enough. I think it's powerful to be able to create "parsing groups" like the `"Structures modification"`. Otherwise you need to select the calcfunctions one by one. Also it is not straightforward because some general parsing is needed before using the actual `@calcfunction` (see `modify_structure` in the `iterate_params` file).

**Comment by pfebrer96** [comment]
> Maybe for my EoS I want to expose the metadata and use a namespace.

Ok, in that case you redefine `_exclude_params_lookup`, but you'd have to do it with your approach as well, wouldn't you? :)

**Comment by bosonie** [comment]
I see very difficult to maintain something like that. I'm considering for instance the fact that soon we will add support for LUA files. In your idea, every possible functionality of lua should also become a parameter to iterate over.
It is, in general, very risky to say that everything is supported when, potentially, there is an infinite spectrum of possibilities.

Anyway, I guess the main point here is that we do not agree. I foresee a long discussion and a even longer development if we go in your direction.  For this I believe it is better to close this PR reverting to previous commit and open  new one. I would like to have the EoS as an example of the use of an iterator and then rethink the rest.

**Comment by pfebrer96** [comment]
I moved back the structure modifications only to the EOS workchain, although I honestly think that by doing this we are missing some potential for the `SiestaIterator` :).

I also added a first draft of automatic description of the parameters in an iterator, as we discussed. You can check it out by doing:

```python
from aiida_siesta.workflows.iterate import SiestaIterator

print(SiestaIterator.parameters_help)
```

Cheers!

**Review by bosonie — APPROVED** [review]

**Pull request merged**
